"""Build deterministic NocoBase metadata and UI migration from reviewable sources."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sql = []
def emit(text): sql.append(text)
def q(value):
    if value is None: return 'NULL'
    if isinstance(value, bool): return 'true' if value else 'false'
    if isinstance(value, (int, float)): return str(value)
    if isinstance(value, (dict, list)): value = json.dumps(value, separators=(',', ':'))
    return "'" + str(value).replace("'", "''") + "'"
def insert(table, row, conflict='DO NOTHING'):
    columns = ','.join('"'+x+'"' for x in row)
    emit(f'INSERT INTO "{table}" ({columns}) VALUES ({",".join(q(x) for x in row.values())}) ON CONFLICT {conflict};')

emit('-- Generated by scripts/build-sprint3.py. Run before starting NocoBase.\nBEGIN;')
emit('''
CREATE TABLE IF NOT EXISTS "attendanceEvents" (
 id bigint PRIMARY KEY, name varchar(255) NOT NULL, "venueId" bigint NOT NULL REFERENCES venues(id),
 "startsAt" timestamptz, status varchar(255) NOT NULL DEFAULT 'active' CHECK (status IN ('active','closed')),
 "totalEntries" bigint NOT NULL DEFAULT 0 CHECK ("totalEntries" >= 0),
 "totalExits" bigint NOT NULL DEFAULT 0 CHECK ("totalExits" >= 0),
 "currentInside" bigint NOT NULL DEFAULT 0 CHECK ("currentInside" >= 0),
 "createdAt" timestamptz, "updatedAt" timestamptz, "createdById" bigint, "updatedById" bigint,
 CHECK ("currentInside" = "totalEntries" - "totalExits")
);
''')
for table in ['entryRecords', 'exitRecords']:
    emit(f'''CREATE TABLE IF NOT EXISTS "{table}" (
      id bigint PRIMARY KEY, "eventId" bigint NOT NULL REFERENCES "attendanceEvents"(id),
      "entranceId" bigint NOT NULL REFERENCES entrances(id), "requestKey" varchar(128) NOT NULL UNIQUE,
      "createdAt" timestamptz, "updatedAt" timestamptz, "createdById" bigint, "updatedById" bigint
    );
    CREATE INDEX IF NOT EXISTS "{table}_event_time" ON "{table}" ("eventId", "createdAt" DESC);''')
emit('''
CREATE OR REPLACE FUNCTION clicker_record_attendance() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE ev "attendanceEvents"%ROWTYPE; place venues%ROWTYPE; station entrances%ROWTYPE; delta integer;
BEGIN
  delta := CASE WHEN TG_TABLE_NAME = 'entryRecords' THEN 1 ELSE -1 END;
  IF NEW."requestKey" IS NULL OR length(NEW."requestKey") < 8 THEN
    RAISE EXCEPTION 'A request ID of at least 8 characters is required';
  END IF;
  SELECT * INTO ev FROM "attendanceEvents" WHERE id = NEW."eventId" FOR UPDATE;
  IF NOT FOUND OR ev.status <> 'active' THEN RAISE EXCEPTION 'Select an active event'; END IF;
  SELECT * INTO place FROM venues WHERE id = ev."venueId" FOR UPDATE;
  SELECT * INTO station FROM entrances WHERE id = NEW."entranceId" FOR SHARE;
  IF NOT FOUND OR NOT station.active OR station."venueId" <> ev."venueId"
    OR station."directionType" NOT IN ('both', CASE WHEN delta = 1 THEN 'in' ELSE 'out' END) THEN
    RAISE EXCEPTION 'Select an active station for this event and direction';
  END IF;
  IF delta = 1 AND place.status <> 'open' THEN RAISE EXCEPTION 'Venue is closed for entry'; END IF;
  IF delta = 1 AND (place."maxCapacity" IS NULL OR place."currentCount" >= place."maxCapacity") THEN
    RAISE EXCEPTION 'Venue is at capacity';
  END IF;
  IF delta = -1 AND (ev."currentInside" <= 0 OR place."currentCount" <= 0) THEN
    RAISE EXCEPTION 'Attendance is zero; an exit cannot be recorded';
  END IF;
  UPDATE "attendanceEvents" SET "currentInside" = "currentInside" + delta,
    "totalEntries" = "totalEntries" + CASE WHEN delta = 1 THEN 1 ELSE 0 END,
    "totalExits" = "totalExits" + CASE WHEN delta = -1 THEN 1 ELSE 0 END,
    "updatedAt" = now(), "updatedById" = NEW."createdById" WHERE id = ev.id;
  UPDATE venues SET "currentCount" = "currentCount" + delta, "updatedAt" = now(),
    "updatedById" = NEW."createdById" WHERE id = place.id;
  NEW."createdAt" := now(); NEW."updatedAt" := now();
  RETURN NEW;
END; $$;
CREATE OR REPLACE FUNCTION clicker_immutable_record() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Attendance records are append-only'; END; $$;
''')
for table in ['entryRecords', 'exitRecords']:
    emit(f'''DROP TRIGGER IF EXISTS clicker_record ON "{table}";
    CREATE TRIGGER clicker_record BEFORE INSERT ON "{table}" FOR EACH ROW EXECUTE FUNCTION clicker_record_attendance();
    DROP TRIGGER IF EXISTS clicker_immutable ON "{table}";
    CREATE TRIGGER clicker_immutable BEFORE UPDATE OR DELETE ON "{table}" FOR EACH ROW EXECUTE FUNCTION clicker_immutable_record();''')

def field(collection, name, type_, interface, title, options=None):
    components = {'input': 'Input', 'integer': 'InputNumber', 'datetime': 'DatePicker', 'm2o': 'AssociationField', 'select': 'Select'}
    opts = {'uiSchema': {'title': title, 'x-component': components.get(interface, 'Input')}}
    if options: opts.update(options)
    insert('fields', {'key': 's3_' + collection + '_' + name, 'name': name, 'type': type_, 'interface': interface,
        'collectionName': collection, 'options': opts, 'sort': 20 + len(sql)})

for i, (table, title) in enumerate([('attendanceEvents','Attendance events'),('entryRecords','Entry records'),('exitRecords','Exit records')]):
    insert('collections', {'key': 's3_'+table, 'name': table, 'title': title, 'inherit': False, 'hidden': False,
        'options': {'template':'general','logging':True,'autoGenId':False,'titleField': 'name' if i==0 else 'id'},
        'description': 'Sprint 3 attendance data', 'sort':30+i})
    emit(f'''INSERT INTO fields (key,name,type,interface,"collectionName",options,sort)
    SELECT 's3_{table}_' || name,name,type,interface,'{table}',options,sort FROM fields
    WHERE "collectionName"='venues' AND name IN ('id','createdAt','updatedAt','createdBy','updatedBy') ON CONFLICT DO NOTHING;''')
    if i == 0:
        field(table,'name','string','input','Event name', {'allowNull':False})
        field(table,'venue','belongsTo','m2o','Venue',{'target':'venues','foreignKey':'venueId','targetKey':'id'})
        field(table,'startsAt','date','datetime','Starts at')
        field(table,'status','string','select','Status',{'defaultValue':'active','enum':[{'label':'Active','value':'active'},{'label':'Closed','value':'closed'}]})
        for name,title in [('totalEntries','Total entries'),('totalExits','Total exits'),('currentInside','Currently inside')]:
            field(table,name,'bigInt','integer',title,{'defaultValue':0})
    else:
        field(table,'event','belongsTo','m2o','Event',{'target':'attendanceEvents','foreignKey':'eventId','targetKey':'id'})
        field(table,'entrance','belongsTo','m2o','Station',{'target':'entrances','foreignKey':'entranceId','targetKey':'id'})
        field(table,'requestKey','string','input','Request ID',{'unique':True,'allowNull':False})

# Carry forward the team's existing occupancy without altering its venues or earlier records.
for eid, venueid, name in [(390000000000001,383436853477376,'Harbor Community Night'),(390000000000002,383436853477377,'Eastside Open Gym')]:
    emit(f'''INSERT INTO "attendanceEvents" (id,name,"venueId","startsAt",status,"totalEntries","totalExits","currentInside","createdAt","updatedAt","createdById","updatedById")
    SELECT {eid},{q(name)},id,'2026-10-01 18:00:00-04','active',"currentCount",0,"currentCount",now(),now(),1,1
    FROM venues WHERE id={venueid} ON CONFLICT DO NOTHING;''')
emit('''INSERT INTO "attendanceEvents" (id,name,"venueId","startsAt",status,"totalEntries","totalExits","currentInside","createdAt","updatedAt","createdById","updatedById")
SELECT 390000000000003,'Harbor Workshop',id,'2026-09-25 18:00:00-04','closed',420,420,0,now(),now(),1,1
FROM venues WHERE id=383436853477376 ON CONFLICT DO NOTHING;''')

# Dedicated course-demo accounts use the same documented demo password as the seed admin.
seed = (ROOT/'seed/prototype.sql').read_text()
start=seed.index('COPY public.users '); lines=seed[start:seed.index('\n\\.',start)].splitlines()
demo_hash=next(line.split('\t')[7] for line in lines[1:] if line.split('\t')[0]=='1')
for i, (role,title) in enumerate([('entry','Entryway attendant'),('exit','Exit attendant'),('manager','Attendance manager')]):
    role='clicker_'+role
    emit(f'''INSERT INTO roles ("createdAt","updatedAt",name,title,strategy,"default",hidden,"allowConfigure","allowNewMenu",snippets,sort)
    VALUES (now(),now(),{q(role)},{q(title)},'{{"actions":[]}}',false,false,false,false,'["!ui.*","!pm","!pm.*"]',{10+i}) ON CONFLICT DO NOTHING;''')
    insert('dataSourcesRoles', {'id':'s3_'+role,'roleName':role,'dataSourceKey':'main','strategy':{'actions':[]}})
    emit(f'''INSERT INTO users (id,"createdAt","updatedAt",nickname,username,email,password,"appLang",sort)
    VALUES ({390000000000101+i},now(),now(),{q(title)},{q(role)},{q(role.replace('clicker_','')+'@clicker.test')},{q(demo_hash)},'en-US',{10+i}) ON CONFLICT DO NOTHING;
    INSERT INTO "rolesUsers" ("createdAt","updatedAt","default","roleName","userId")
    VALUES (now(),now(),true,{q(role)},{390000000000101+i}) ON CONFLICT DO NOTHING;''')
    resources={'venues':['view'],'entrances':['view'],'attendanceEvents':['view']}
    if role=='clicker_manager':resources.update({'entryRecords':['view'],'exitRecords':['view']})
    else:resources['entryRecords' if role=='clicker_entry' else 'exitRecords']=['view','create']
    for j,(res,actions) in enumerate(resources.items()):
        rid=390000000001000+i*100+j
        emit(f'''INSERT INTO "dataSourcesRolesResources" (id,"createdAt","updatedAt","roleName",name,"usingActionsConfig")
        VALUES ({rid},now(),now(),{q(role)},{q(res)},true) ON CONFLICT DO NOTHING;''')
        for k,action in enumerate(actions):
            fields=['eventId','entranceId','requestKey'] if action=='create' else None
            emit(f'''INSERT INTO "dataSourcesRolesResourcesActions" (id,"createdAt","updatedAt","rolesResourceId",name,fields)
            VALUES ({390000000010000+i*1000+j*10+k},now(),now(),{rid},{q(action)},{q(fields)}) ON CONFLICT DO NOTHING;''')

def model(uid, options):
    insert('flowModels',{'uid':uid,'name':uid,'options':options},'(uid) DO UPDATE SET options=EXCLUDED.options')
def path(ancestor,descendant,depth,async_=None,type_=None,sort=None):
    insert('flowModelTreePath',{'ancestor':ancestor,'descendant':descendant,'depth':depth,'async':async_,'type':type_,'sort':sort})
for i,(mode,title) in enumerate([('entry','Entryway attendant'),('exit','Exit attendant'),('manager','Manager attendance')]):
    rid=390000000000200+i*2; tid=rid+1
    root,tab,page,grid,block=[f's3_{mode}_{x}' for x in ['route','tab','page','grid','block']]
    for route_id, parent, route_title,schema,typ,hidden,order in [(rid,None,title,root,'flowPage',False,-3+i),(tid,rid,None,tab,'tabs',True,1)]:
        emit(f'''INSERT INTO "desktopRoutes" (id,"createdAt","updatedAt","parentId",title,"schemaUid","menuSchemaUid","tabSchemaName",type,sort,"hideInMenu","enableTabs",hidden,"createdById","updatedById")
        VALUES ({route_id},now(),now(),{q(parent)},{q(route_title)},{q(schema)},{q(root+'_menu') if not hidden else 'NULL'},{q(tab+'_name') if hidden else 'NULL'},{q(typ)},{order},false,false,{q(hidden)},1,1) ON CONFLICT DO NOTHING;
        INSERT INTO "main_desktopRoutes_path" ("nodePk",path,"rootPk")
        SELECT {route_id},{q('/'+str(rid)+('/'+str(tid) if hidden else ''))},{rid}
        WHERE NOT EXISTS (SELECT 1 FROM "main_desktopRoutes_path" WHERE "nodePk"={route_id});''')
        for role in ['admin','clicker_'+mode]:
            emit(f'''INSERT INTO "rolesDesktopRoutes" ("createdAt","updatedAt","desktopRouteId","roleName")
            VALUES (now(),now(),{route_id},{q(role)}) ON CONFLICT DO NOTHING;''')
    model(root,{'schema':{'use':'RouteModel'}});model(tab,{'schema':{'use':'RouteModel'}})
    model(page,{'parentId':root,'subKey':'page','subType':'object','use':'RootPageModel','props':{},'stepParams':{},'sortIndex':0,'flowRegistry':{}})
    layout={'rows':{'row1':[[block]]},'sizes':{'row1':[24]},'rowOrder':['row1']}
    model(grid,{'parentId':tab,'subKey':'grid','subType':'object','use':'BlockGridModel','props':layout,'stepParams':{'gridSettings':{'grid':layout}},'sortIndex':0,'flowRegistry':{},'filterManager':[]})
    code=(ROOT/'ui'/('manager.js' if mode=='manager' else 'attendant.js')).read_text().replace('__MODE__',mode)
    model(block,{'parentId':grid,'subKey':'items','subType':'array','use':'JSBlockModel','props':{},'stepParams':{'jsSettings':{'runJs':{'version':'v2','code':code}}},'sortIndex':1,'flowRegistry':{}})
    path(root,root,0,False);path(tab,tab,0,False);path(page,page,0,True,'page');path(root,page,1,None,None,1)
    path(grid,grid,0,False,'grid');path(tab,grid,1,None,None,1)
    path(block,block,0,False,'items');path(grid,block,1,None,None,1);path(tab,block,2,None,None,1)
emit('COMMIT;')
(ROOT/'scripts/migrate-sprint3.sql').write_text('\n'.join(sql)+'\n')
print('Built scripts/migrate-sprint3.sql')
